name: Python Guvenlik Zinciri

# Bu akış ne zaman çalışsın?
on:
  push:
    branches: [ "main" ]

jobs:
  guvenli-paketleme:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # Cosign için gerekli izin

    steps:
      # 1. Adım: Kodları GitHub'dan çek
      - name: Kodlari Cek
        uses: actions/checkout@v4

      # 2. Adım: İmzalama aracını (Cosign) kur
      - name: Cosign Kur
        uses: sigstore/cosign-installer@v3.3.0

      # 3. Adım: Tarama aracını (Syft) kur
      - name: Syft Kur
        uses: anchore/sbom-action/download-syft@v0.15.0

      # 4. Adım: Python uygulamasını Alpine ile paketle (Minimal İmaj)
      - name: Minimal Imaj Olustur
        run: docker build -t ttl.sh/sinan-python-demo:${{ github.sha }} .

      # 5. Adım: İmajın içindekiler listesini (SBOM) çıkar
      - name: SBOM Olustur
        run: syft ttl.sh/sinan-python-demo:${{ github.sha }} -o spdx-json > sbom.json

      # 6. Adım: SBOM dosyasını kanıt olarak kaydet
      - name: SBOM Dosyasını Yükle
        uses: actions/upload-artifact@v4
        with:
          name: sbom-listesi
          path: sbom.json

      # 7. Adım: İmajı depoya gönder
      - name: Imaji Gonder (Push)
        run: docker push ttl.sh/sinan-python-demo:${{ github.sha }}

      # 8. Adım: İmajı gizli anahtarla imzala (Sign)
      - name: Imaji Imzala (Sign)
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ttl.sh/sinan-python-demo:${{ github.sha }}
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      # 9. Adım: Doğrulama testi yap (Verify)
      - name: Dogrulama Testi (Verify)
        run: |
           cosign verify --key cosign.pub ttl.sh/sinan-python-demo:${{ github.sha }}